### ISSUE TITLE
Raid Illagers Spawning Underground

### ISSUE THREAD

**Issue by Cisceaugh** [Thelnfamous1/Dungeons-Mobs#10]
Initiating a raid will cause the Illagers to spawn underground. Seen as low as y = 37

Tested on:
- dungeons_mobs-1.16.4-1.0.3
- dungeons_gear-1.16.4-3.0.6

**Comment by Thelnfamous1** [comment]
Can you specify which illagers and in which biomes? Something tells me mountain raids are the issue

**Comment by Thelnfamous1** [comment]
I have found the solution for this, and I will upload a fixed version soon
