### ISSUE TITLE
Royal Guard AI seems buggy when he uses a shield

### ISSUE THREAD

**Issue by zEpiixz** [Thelnfamous1/Dungeons-Mobs#11]
I use Dungeon Gear and Dungeon Mobs only.

The royal guard just puts up his shield when i go close to them and never charged a single attack.
I stood between royal guards for good 3 minutes without anyone even trying to attack me so they posses no threat at all.
Im not sure if this behavior is intended.

**Comment by Thelnfamous1** [comment]
Intended currently, but planned to have a smarter attacking system while actively shielding

**Comment by Thelnfamous1** [comment]
Fixed in dev, will be fixed in next release
