### ISSUE TITLE
Mages and Illusioners cant clone

### ISSUE THREAD

**Issue by a-random-something** [Thelnfamous1/Dungeons-Mobs#112]
Their clones just instantly disappear when they spawn, even when using /summon. I'm using all the mods from https://www.curseforge.com/minecraft/modpacks/village-and-pillage-2-0 forge 36.2.20 dungeons mobs beta 2.0.3
EDIT: Tried updating to forge 36.2.34 and going back in versions of the mod, but neither worked.
EDIT 2: Tried just dungeons mobs with only its dependencies and it works there, so it's probably a mod compatibility issue

**Comment by people04** [comment]
Because the Mage and Illusioner clones do not have nbt control living tick

**Comment by Patrigan** [comment]
Mages and illusioners properly clone now
