### ISSUE TITLE
Game crashes during fights

### ISSUE THREAD

**Issue by Bater-Wucket** [Thelnfamous1/Dungeons-Mobs#116]
I decided to make a mob battle and the game crashed during Royal guard and Armored mountaineer's fight (I made some battles before that and there were no crashes). I played with Guard villagers mod and game crashed too

The crash report:

[crash-2022-09-04_17.34.00-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/9484897/crash-2022-09-04_17.34.00-server.txt)

**Comment by people04** [comment]
enchanter makes crash it

**Comment by people04** [comment]
Not mod incompatible

**Comment by Patrigan** [comment]
No longer a problem, as the enchanter is now disabled.
