### ISSUE TITLE
[1.16.5] Server crashes randomly with Ticking Entity

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Mobs#12]
I suspect it is Dungeons Mobs causing this based on the prominent errors here:

[crash-2021-02-22_01.17.09-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/6019539/crash-2021-02-22_01.17.09-server.txt)

**Comment by Thelnfamous1** [comment]
I'll look into this, likely something affecting the Frozen Zombie's snowball throwing AI

**Comment by Thelnfamous1** [comment]
Fixed in dev, will be fixed in next release
