### ISSUE TITLE
Ensorcellation & Elenai Dodge 2 mod conflict

### ISSUE THREAD

**Issue by TheFlame52** [Thelnfamous1/Dungeons-Mobs#133]
When Dungeons Mobs, Elenai Dodge 2, and Esorcellation are all installed, if a player is shot by a bow enchanted with the Trueshot enchantment, the game hangs. I can't provide any more details. In singleplayer, there is no crash log. Attached is a crashlog from a RAD 2 server which experienced the bug.
[crash-2022-09-21_00.18.09-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/9629863/crash-2022-09-21_00.18.09-server.txt)

**Comment by Patrigan** [comment]
Fixed in latest beta :)
