### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by ShootToKillSTK** [Thelnfamous1/Dungeons-Mobs#14]
Appears to be from this mod, or maybe something else doing somethint to it. Crashing occurs in nether, probably happen in oveworld/anywhere though

https://gist.github.com/ShootToKillSTK/9a6e0475e86fb6b0b600af587f909521

**Comment by belathus** [comment]
Got a similar, but different, crash: https://gist.github.com/belathus/569038881f4a655c3e5321597cf194f0

**Comment by Thelnfamous1** [comment]
Quick glance tells me that the Skeleton Vanguard is having some compatibility issues with its shield usage AI, I'll bring this up with the team

**Comment by Thelnfamous1** [comment]
Fixed in dev, will be fixed in next release
