### ISSUE TITLE
Wildfire summon mob crash  1.16.5 - 2.1.2 beta

### ISSUE THREAD

**Issue by Sageking10** [Thelnfamous1/Dungeons-Mobs#146]
I had some custom npcs fight the wildfire and the game suddenly crashed when he summoned some mobs.
[https://crashy.net/2WrxMBDD8NwoIpUNBXQ5](url)
[crash-2022-11-23_15.11.53-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/10078918/crash-2022-11-23_15.11.53-server.txt)

**Comment by Patrigan** [comment]
Issue will be fixed in the upcoming release.

**Comment by Patrigan** [comment]
fixed a while ago
