### ISSUE TITLE
World Freezing

### ISSUE THREAD

**Issue by SuperTiru** [Thelnfamous1/Dungeons-Mobs#148]
When the RoadRunner moe and the Dungeons Mobs mod are used together, the game stops on the sea biome side.
The chunk is not loaded, mob cannot be attacked, command is not used, and it loads indefinitely at the end of the game.
The method of implementing a crash is to use the above two mods together and then fly around the sea biome in creative mode. there's a crash in five minutes.
There is no information left in the log and debug files because the game is frozen rather than crashed. 
Of course, a crash report is not generated either.
The mods used in the Test are the latest versions.
![test](https://user-images.githubusercontent.com/108540864/204116022-892c4706-071a-49c8-81ab-9b2afa128791.png)

**Comment by SuperTiru** [comment]
If i modify from roadrunner config to mixin.world=false, it is confirmed that the crash does not occur

**Comment by SuperTiru** [comment]
The cause has been found.
This problem occurs when ```enableEliteMobs = true``` in the config of the dungeons Libraries
I will attach the related crash report.
[crash-2022-11-27_12.53.23-fml.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/10097489/crash-2022-11-27_12.53.23-fml.txt)

If i need to move the issue to the issue tab in dungeons Libraries mod, I will.

**Comment by antibang** [comment]
I can add that I also have this issue :( however, the issue of deadlocking/crashing persists even if I disable the elite mobs, but it does improve the situation. It doesn't lock up as much, but unfortunately my modpack is pretty unplayable when Dungeons Mobs and RoadRunner are both present. I really don't want to have to say goodbye to either mod! 

After multiple days of testing and searching through logs and debugs, I have the sad issue of literally nothing printing out that'd be useful in the slightest. Although, at the end of my debugs, there's some mixin info printing out, not very many being specifically RoadRunner mixins, but that's *usually* around the point it deadlocks. It's usually something about mob AI or entity tracking. Not sure if that has anything to do with the situation (considering RoadRunner is basically just mixins).

Even though that paragraph was a bit hypocritical, I continue to have the issue when both mods are present, regardless of changing the Dungeons Mobs config and changing `mixin.world=false` in the RoadRunner config. My issue is completely fixed if I remove one or the other mod from my modpack.

**Comment by Patrigan** [comment]
So it seems we have indeed an incompatibility with RoadRunner. I will try to do some debugging and see if I can fix it.

The thing is that Performance Mods like RoadRunner, often work by disabling certain things. It's very possible here they're disabling something they shouldn't. I'm not sure Dungeons Mobs will be able to fix this, so make sure to report it to the roadrunner team as well.

**Comment by Patrigan** [comment]
This bug should now be fixed with latest libraries
