### ISSUE TITLE
[Suggestion] Ragdoll deaths and Redstone Golem's mine attack

### ISSUE THREAD

**Issue by firecatboy97** [Thelnfamous1/Dungeons-Mobs#150]
Well I want ask about the two thing in question I had in my mind.

1. Is it possible for you guys to add in Ragdoll deaths to the mobs in this mod (even if you have to make it's a separate mod) similar to that of the original game?

2. about the Redstone Golem's mine attack is it also possible for you guys to add in the non-active state of the mine (where it loses power, becomes a powerless black block, then begins to shrink to a smaller block before disappering after a certain period after the attack was first used.)?

**Comment by Patrigan** [comment]
1. We likely won't do this. Playing with animations and mob models is a time consuming thing. Plus there's always a big risk of mod incompatibilities. It would also mean we're going to have to fiddle with vanilla mobs, which is, again, pretty dangerous territory.
2. We can look into this one. Would make sense.

**Comment by firecatboy97** [comment]
Thank you for the answers, it's just this mod and Dungeons gear is so good in capturing the Minecraft Dungeons experience.
Tho I do have two more questions.

1. Is there going to be compatibility with Obscuria's mods like Aquamirae since the illagers mobs are part of it and also compatibility the mod It Takes a Pillage as well? 

2. with the mods Dungeons Bosses mod and Mobs Animations Plus existing. is it going to be any plans to contact the creators of the mods in question?
