### ISSUE TITLE
[Bug] Illager Animations Broken

### ISSUE THREAD

**Issue by VanyaBaou** [Thelnfamous1/Dungeons-Mobs#151]
With Dungeons Gear + Mobs + Library (and dependencies curios + geckolib), animations break for Illagers.
Haven't looked at _every_ mob to see if it happens elsewhere.

Video [here](https://streamable.com/mgqv4f)

Mods: (Forge 36.2.33)
![image](https://user-images.githubusercontent.com/97327658/207213791-561b36d4-6045-45d1-81bc-080b0c628aa7.png)

**Comment by Patrigan** [comment]
Fixed in 2.2.2
