### ISSUE TITLE
Glitchy view while stuck in spider webs

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Mobs#158]
The physics for spider web seems to be a bit buggy (no pun intended): 
- You can get stuck on top of the web and your view is constantly attempting to drop. It may be better to allow players to drop down to the block the web is on and/or only prevent horizontal movement while in the air
- The view is very shaky while stuck in web, as if it's spamming a position set rather than disabling movement

**Comment by MarioSMB** [comment]
As a side-note, I wonder if copying the way Minecraft's spider webs are handled would help with the glitching view issue; the movement-slowing effect could be increased to the point where the player doesn't move. Falling speed could remain the same as vanilla spider webs so as to fix the first point.

**Comment by Patrigan** [comment]
I like your suggestion, I've noticed the same and it's on my todo list. I will take a look at the code for it.

**Comment by Thelnfamous1** [comment]
A short-term fix was added in 4.0.8.
