### ISSUE TITLE
[1.18.2] Crashing as soon as i spot a pillager

### ISSUE THREAD

**Issue by Akaixz** [Thelnfamous1/Dungeons-Mobs#159]
So i'm trying to track a crash that is happening as soon as i spot a pillager (i cant join the world after that), and i think it's something like a pillager trying to use an armor from the mod "dungeons_gear"

Crash Report: https://pastebin.com/xNGkKckE

**Comment by Patrigan** [comment]
Yes, sadly. This is a known issue, I'm waiting for new models from our modellers in order to fix this.

**Comment by Akaixz** [comment]
Theres a workaround fix for this?

**Comment by Patrigan** [comment]
Fix should now be released to CF.

Version 3.0.2-beta
