### ISSUE TITLE
[Suggestion] Option to disable mobs dropping their items

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Mobs#160]
There's a config option to disable mobs from dropping their armor, but none exists for other items (artifacts, shields, weapons).  
An option to disable dropping items as well would be nice, thanks!

**Comment by Thelnfamous1** [comment]
As far as I know, those are controllable through datapack - you override the mob's loot table file and replace it with whatever you deem appropriate. Mobs dropping their armor is something handled only internally, which is why we provide an option to disable it.

**Comment by MarioSMB** [comment]
I've been digging through the data files and have yet to find a way to disable item drops like the shields - even when removed from the body pieces vanguards will still drop their shield no matter what. They seem to be handled in a similar manner to armor.  

Interestingly their held items are classified as "boss gear", although some pieces do indeed appear to be hardcoded.

**Comment by MarioSMB** [comment]
Can confirm, here is the geomancer loot table: https://github.com/Infamous-Misadventures/Dungeons-Mobs/blob/1.18/src/main/resources/data/dungeons_mobs/loot_tables/entities/geomancer.json  
But it still has a low chance to drop the Geomancer Staff artifact (dungeons_mobs:geomancer_staff), which is hardcoded as a hand item here: https://github.com/Infamous-Misadventures/Dungeons-Mobs/blob/1.18/src/main/java/com/infamous/dungeons_mobs/entities/illagers/GeomancerEntity.java#L152  

Indeed, from what I can tell item drops are hardcoded the same way armor is in the mod currently, an option to change it would be much appreciated!

**Comment by Thelnfamous1** [comment]
Oops, that's my bad, I read your question as wanting to control their loot drops. I see no reason why we cannot additionally include the config options for their held items as well.

**Comment by Thelnfamous1** [comment]
Added the config option to toggle our mobs dropping their held items.
