### ISSUE TITLE
Piglin variants don't trigger Oh Shiny achievement

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Mobs#162]
The piglin variants (namely fungus throwers) can be bartered with, but they don't give the player the "Oh Shiny" achievement.

**Comment by Thelnfamous1** [comment]
Hmm, that sounds like we need to override the advancement via datapack to include the fungus throwers as well.

**Comment by Thelnfamous1** [comment]
Fixed for next 1.19.2 release.
