### ISSUE TITLE
Fungus Thrower attacks wither skeletons

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Mobs#163]
When near a wither skeleton, fungus throwers will constantly throw their poison bottles at them which does nothing as wither skeletons are immune to the effect.

**Comment by Thelnfamous1** [comment]
So, they are intended to be like Piglins and attack the Wither Skeletons, but - I forgot that poison doesn't affect undead mobs. Looks like we'll have to give them a different status effect like "Warped" or something that can still work on undead mobs.

**Comment by Thelnfamous1** [comment]
Fixed for next 1.19.2 release (pending an additional fix in Dungeons Gear 1.19.2).
