### ISSUE TITLE
[Suggestion] Option to Disable Artifact GUI on Screen

### ISSUE THREAD

**Issue by big-tdawg** [Thelnfamous1/Dungeons-Mobs#164]
I would like to suggest an option to disable the three artifact inventory slots that appear in the bottom right side of the screen. The extra GUI just makes the screen a bit more clustered and I feel it is not necessary to the gameplay. 

Terrific mod by the way!!

**Comment by Ezeyra** [comment]
Very much agree, maybe also an option to move it's position?

**Comment by Thelnfamous1** [comment]
Dungeons Gear issue. The 3 slots no longer appear unless you have an artifact equipped in one of them, and there is a datapack available on the Discord to completely remove them. I will figure out a way to make that datapack accessible from the front page of Dungeons Gear.
