### ISSUE TITLE
Ultra Fast Attack Bug with Fighter's Bindings and any other Weapon (Better Combat + Dungeons Gear)

### ISSUE THREAD

**Issue by yarago666** [Thelnfamous1/Dungeons-Mobs#171]
With Better Combat if you take a Fighter's Bindings in your left hand and, for example, an anchor or other slow weapon in your right, sometimes a fast attack bug can work. but, the damage will be max and the attack speed will be like the bindings you use.

**Comment by Patrigan** [comment]
Can you verify this still works on latest? We literally just released a fix for a similar spammy attack issue :)

**Comment by Thelnfamous1** [comment]
This is a Dungeons Libraries bug, and it has been confirmed fixed in latest versions. https://github.com/Infamous-Misadventures/Dungeons-Libraries/commit/2bc6c309203af6a7b3355001ea220cd3201c09cb
