### ISSUE TITLE
Poison Anemones naturally spawning

### ISSUE THREAD

**Issue by kaairu** [Thelnfamous1/Dungeons-Mobs#174]
Poison Anemones don't spawn normally, they are summoned by wave whisperers. With the current spawns, they fall from the sky and slowly fall to the bottom of the ocean. 
![image](https://user-images.githubusercontent.com/121336317/217736986-c691ff67-c760-4c03-ab05-6a77f279022a.png)

**Comment by Thelnfamous1** [comment]
This was fixed in 4.0.5:
https://github.com/Infamous-Misadventures/Dungeons-Mobs/commit/3af6a52b489771f5de767eb7538d9cc9f2cb11ed
