### ISSUE TITLE
villagers plus n dungeons mobs conflict 

### ISSUE THREAD

**Issue by kaairu** [Thelnfamous1/Dungeons-Mobs#183]
someone said villagers plus is conflicting w dungeons mobs. i insta crash when I load into a prev saved world.

[launcher_log.txt](https://github.com/Infamous-Misadventures/Dungeons-Mobs/files/11168174/launcher_log.txt)
[latest.log](https://github.com/Infamous-Misadventures/Dungeons-Mobs/files/11168175/latest.log)
[crash-2023-04-05_23.34.27-client.txt](https://github.com/Infamous-Misadventures/Dungeons-Mobs/files/11168176/crash-2023-04-05_23.34.27-client.txt)

**Comment by Thelnfamous1** [comment]
~~Try removing or updating Epic Fight Mod, that is the only thing that comes up in my research to diagnose the issue.~~ NVM, looks like you don't have that as you are in 1.19.2.
