### ISSUE TITLE
[Suggestion] Epic Fight Light Compatibility

### ISSUE THREAD

**Issue by Quizer9O8** [Thelnfamous1/Dungeons-Mobs#19]
Illagers, Zombies and Skeletons of this mod ignore every aspect of Epic Fight. Can they be made compatible to work with that mod?

**Comment by Thelnfamous1** [comment]
Most likely, Epic Fight would need to establish compatibility. But I am not familiar with what exactly it is doing with Illagers, Zombies and Skeletons.

**Comment by BraveCaperCat** [comment]
That issue was closed, so i'm assuming that it's a can't/won't fix, maybe adding compat from this mod will fix this?
