### ISSUE TITLE
[Suggestion]About Enchanter's voice.

### ISSUE THREAD

**Issue by jn-njjp** [Thelnfamous1/Dungeons-Mobs#198]
This mod is recommended for use with EnchantWithMob, but in EnchantWithMob, the Enchanter's voice is replaced with the Illusioner's voice. How about making it possible to play the Enchanter's voice and the sound of magic effects by using this mod together?

**Comment by who-are-you6900** [comment]
I don't think that's happening. I'm pretty sure it violates Mojang EULA.
