### ISSUE TITLE
Armored Skeleton Crash

### ISSUE THREAD

**Issue by Eustisa** [Thelnfamous1/Dungeons-Mobs#2]
[crash-2020-12-20_01.02.40-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/5720411/crash-2020-12-20_01.02.40-server.txt)

**Comment by Thelnfamous1** [comment]
Ask Vazkii (Botania dev) about this, it points to Botania as the source of the problem.

**Comment by BraveCaperCat** [comment]
Maybe you should actually read those crash logs, as i know exactly which mod caused my issues just by looking at the crash logs!

**Comment by Patrigan** [comment]
Armored Skeletons no longer exist.
