### ISSUE TITLE
Skeleton Horsemen spawning way too much

### ISSUE THREAD

**Issue by Joftenin** [Thelnfamous1/Dungeons-Mobs#20]
I'm playing on the Better Minecraft Modpack, I'm having several skeleton horsemen groups spawn in one night, it is getting to the point where I can't even build anything because a new group spawns. 
I have dungeons_mobs-1.16.4-1.0.4.jar

**Comment by Thelnfamous1** [comment]
Are you using performant? We've found out that was the cause of an insane dupe bug with Skeleton horse spawns

**Comment by jakecroftford** [comment]
Is there a way to fix it without getting rid of performant as we are having the same issue ending nights with up to hundreds of skele horses overwhelming players at their bases but the performant mod is super helpful
*So as a temp fix i found that performant can disable spawns for mobs in the configs so i simply disabled the skeleton horsemen for now as it was causing issues having mobs overrunning peoples bases even if the player would withstand them the spawning eventually took effect on the players hardware dropping fps and the server dropping tps

**Comment by Thelnfamous1** [comment]
Performant hacks so much AI code, we cannot do anything to fix it on our end.
