### ISSUE TITLE
Ranged Spiders feature not working

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Thelnfamous1/Dungeons-Mobs#22]
Dungeons Mobs Version: 1.0.10
Forge Version: 36.2.2
Minecraft Version: 1.16.5

Hi,

I noticed that when attempting to test out the ranged spiders feature mentioned in the config file, which should make spiders shoot webs like in Minecraft: Dungeons, they just acted like they normally did in Vanilla Minecraft and this feature just didn't work at all. This goes for both spiders and cave spiders (Although it should be noted that in Minecraft Dungeons only regular spiders shoot webs, but that doesn't necessarily matter). 

I'm not sure if this is a feature that is still unfinished or if it's supposed to be fully functional at the moment so I'm reporting this issue here in case it's the latter. If you need any more information about this issue (such as descriptions or logs) then just let me know and I'd be happy to provide it!

(In case it matters I'm only using Dungeons Mobs and not Dungeons Gear)

Thanks for the great mod!

**Comment by Thelnfamous1** [comment]
Logs would be helpful, as I notice no issues in my code that would prevent the feature from working. This is a relatively completed feature so the only issue here would be either the config not affecting functionality or some other mod affecting the spider. Also, you are editing the config file prior to loading up the game, yes? It won't do anything if you edit it mid-game.

**Comment by The-Bernician-Lamb** [comment]
> Logs would be helpful.

Here's my latest log: https://gist.github.com/NJL5390/85a938535efaf96a51873ad420d23447

I'm using the Curseforge launcher in case that will affect anything.

> . Also, you are editing the config file prior to loading up the game, yes? It won't do anything if you edit it mid-game.

Yes. I'm always editing the config before I start up the game. In this case, I had a freshly generated config file and the feature still didn't work.

**Comment by The-Bernician-Lamb** [comment]
Thought I'd include a debug log as well: https://gist.github.com/NJL5390/515411e126c614959458c41c3846f0a9

Just so you know this issue does occur without any other mods installed.

Although, in my main custom modpack (not related to this issue) I have a mod called Spiders 2.0 (https://www.curseforge.com/minecraft/mc-mods/spiders-2-0) which I'm almost certain is going to cause some other issues once this one is resolved since it changes so much about spiders in general. (Again, Spiders 2.0 is not related to this particular issue, I just thought that mod was worth mentioning).

**Comment by Thelnfamous1** [comment]
I'll work on a fix soon, currently I am working on catching up on the DLC additions for Dungeons Gear.

**Comment by Thelnfamous1** [comment]
Does this still occur in the latest release?

**Comment by The-Bernician-Lamb** [comment]
Unfortunately, Yes It still does. I tested with only Dungeons Mobs (1.0.10) installed and this issue still occurred even after generating a new config file. 

I will leave you with this debug log that I got from this exact test session. Maybe you'll see something that will help you?
https://gist.github.com/NJL5390/64049eb05cf26e896f7bd1f214205159

Let me know if you need anything else from me.

**Comment by Thelnfamous1** [comment]
When you have it enabled, is the spider more than 3 blocks away from you when it detects you? I’ve coded it so it defaults to melee AI if the target is within 3 blocks or if the target is already trapped by a web

**Comment by Thelnfamous1** [comment]
Nevermind, I have just retested it, it turns out along the change history I went from it working to flat out not doing anything, fortunately I just got it working again (even better than before) and it should definitely be compatible with Spiders 2.0 as well.

**Comment by Patrigan** [comment]
Working properly in latest version.
