### ISSUE TITLE
Player on server hit by windcaller flew upwards forever

### ISSUE THREAD

**Issue by t-wanderer** [Thelnfamous1/Dungeons-Mobs#23]
A player got hit by a windcaller and received "levitation 9" and flew upwards without end. The clear command did not remove it, and the timer was 0 seconds. Player passed y= 3500. I had to force tp the player into solid rock to stop this via death. This was with the Blutmond modpack with no alterations.

**Comment by Thelnfamous1** [comment]
Windcallers by default do not give their targets levitation 9 nor for a lengthy duration, most likely is some kind of mod affecting levitation application.

**Comment by BraveCaperCat** [comment]
Use /effect @s clear

**Comment by Patrigan** [comment]
No longer relevant, windcaller rewritten
