### ISSUE TITLE
Village Raid causing Exception Ticking World Crash

### ISSUE THREAD

**Issue by lifesbrink** [Thelnfamous1/Dungeons-Mobs#24]
https://pastebin.com/3xEZg9ge

For now, I have disabled all dungeons mobs from the raid, hopefully that fixes the issue. Will run more tests.

I saw this issue from previous versions and figured updating would fix it, but alas.

**Comment by Thelnfamous1** [comment]
I'm not sure what to do about whatever Bukkit is doing here, do they have their own issue tracker? Might be better off handing this information to them

**Comment by Patrigan** [comment]
ALl mobs rewritten and since this is a bukkit issue, closing this now.
