### ISSUE TITLE
Ticking entity... again?

### ISSUE THREAD

**Issue by Dryelo** [Thelnfamous1/Dungeons-Mobs#26]
hi there.

I had two server crashes while I was fighting an armored zombie.

I saw that there are some closed issues here dealing with ticking entity crashes.
Is this supposed to be fixed in the 1.16.5-1.0.5 release?

[crash-2021-06-16_18.44.26-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/6669412/crash-2021-06-16_18.44.26-server.txt)

Thank you for your time developing this mod and dealing with our problems 👍

**Comment by Thelnfamous1** [comment]
Let the Astral Sorcery dev know about this, and possibly the Tetra dev as well

**Comment by Dryelo** [comment]
will do, thank you :)
