### ISSUE TITLE
Hello! I'm creator of Epic Fight Mod and I suggest you modify some code causing crashes with my mod.

### ISSUE THREAD

**Issue by Yesssssman** [Thelnfamous1/Dungeons-Mobs#27]
Your mod directly uses a raw function that is depreciated by Forge. It completely overwrites the attribute map of Husk, therefore it removes the attributes I registered.

com.infamous.dungeons_mobs.worldgen.EntityTypeAttributes, Line 65

GlobalEntityTypeAttributes.put(EntityType.HUSK, HuskEntity.func_234342_eQ_()
                .createMutableAttribute(Attributes.ARMOR, 10.0D)
                .createMutableAttribute(Attributes.MOVEMENT_SPEED, 0.17D)
                .createMutableAttribute(Attributes.KNOCKBACK_RESISTANCE, 0.6D)
                .create());

So whenever Husk spawns, My mod can't find the attribute I registered. It'll lead to NullPointerException.
I recommend you to use EntityAttributeModificationEvent. It'll not overwrite the attribute map from other mods so that improve the compatibility with other mods.

Sincerely,

**Comment by Thelnfamous1** [comment]
Will fix in next release, that event was not a thing when I had written that particular line of code. Thanks for the heads up.
