### ISSUE TITLE
[Suggestion] SFX from Minecraft Dungeons?

### ISSUE THREAD

**Issue by NathanLithia** [Thelnfamous1/Dungeons-Mobs#28]
Hi :)

Would it be possible to port over the Sound effects from Minecraft dungeons for the mobs themselves?
They seem to only play Vanilla Minecraft sounds when I hit them.

For example the Wraith makes Ghast sounds instead of the sounds from the wiki:
[https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Wraith](https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Wraith)

If not, Is there a way I can port them over myself via a ResourcePack?

**Comment by Thelnfamous1** [comment]
It is possible, they will all be added at once in a later update. For now, I am focusing on adding content from the DLCs and fixing bugs (no, the sound effects are not considered bugs).
