### ISSUE TITLE
Game crashes as of latest update whenever a conjured slime is spawned

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Thelnfamous1/Dungeons-Mobs#32]
Dungeons Mobs version: 1.0.8
Forge version: 36.2.2
Minecraft Version: 1.16.5
Crash Report: https://gist.github.com/NJL5390/a6bd1a47870930a6405984a17e5b42ac

Hi,

I noticed recently when trying out the latest update to this mod that whenever I spawned in a conjured slime, the game would crash, this happens no matter how the mob is spawned in, be it via spawn egg or via the In Control mod I'm using.

This only started happening when I updated to the latest version of Dungeons Mobs and was not happening previously. In case you are wondering, this specific crash was triggered by attempting to spawn a conjured slime with a spawn egg.

**Comment by DeltaWolf7** [comment]
Exact same issue here also, all the same versions of everything.
Can provide logs if required.

**Comment by Thelnfamous1** [comment]
Known bug, will be fixed in next update.

**Comment by The-Bernician-Lamb** [comment]
I cannot seem to reproduce this issue anymore as of the latest update! Thanks for your assistance!
