### ISSUE TITLE
Game Crashes when loading up a world with ranged spiders feature disabled

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Thelnfamous1/Dungeons-Mobs#34]
Dungeons Mobs Version: 1.0.10
Forge Version: 36.2.2
Minecraft Version: 1.16.5
Crash Report: https://gist.github.com/NJL5390/6634e6dacaaaed34ac0894fba2e31829

I Found this issue while testing for one of the other issues: (https://github.com/Thelnfamous1/Dungeons-Mobs/issues/22). Whenever I load up a world with ranged spiders disabled the game just crashes with this crash report. If I re-enable the ranged spiders feature then everything works normally and the game doesn't crash. But the ranged spiders feature itself doesn't seem to work anyway because of the issue mentioned earlier.

I don't know if these two issues are related or not but this crash never used to happen in older versions so I doubt it.

**Comment by Thelnfamous1** [comment]
Ah, I can fix this easily, simple mistake.

**Comment by Patrigan** [comment]
No longer gcrashes the game.
