### ISSUE TITLE
newly added drowned incompatility with Upgrade Aquatic's drowned swiming animation

### ISSUE THREAD

**Issue by Wedge1453** [Thelnfamous1/Dungeons-Mobs#36]
they look like they're praying
![2021-08-08_20 31 24](https://user-images.githubusercontent.com/76813383/129033235-46b6994b-1fdc-42c5-b57c-f555629aefc8.png)

**Comment by BraveCaperCat** [comment]
Praying to..........the drowned necromancer?

**Comment by Patrigan** [comment]
Armored drowned no longer exist as they do. Should not be an issue anymore.
