### ISSUE TITLE
minecraft:spider Crash

### ISSUE THREAD

**Issue by Daejangnamu** [Thelnfamous1/Dungeons-Mobs#37]
forge-1.16.5-36.2.2

mod list
jei-1.16.5-7.7.1.118
dungeons_mobs-1.16.5-1.0.10

log: https://gist.github.com/Daejangnamu/c2474390e6595d2e3c6f8e4b56f31dab

**Comment by Patrigan** [comment]
The log is no longer accessible, can you reprovide it.

**Comment by Patrigan** [comment]
Possible duplicate of an earlier bug with ranged spiders disabled?

**Comment by BraveCaperCat** [comment]
Close immediately, not enough info!

**Comment by Patrigan** [comment]
Ranged spiders no longer crash the game
