### ISSUE TITLE
guard royal does not appear in raids and does not appear in mansions. Can you enable it in the raids in the next update?

### ISSUE THREAD

**Issue by FORJATARTARO** [Thelnfamous1/Dungeons-Mobs#4]

**Comment by Thelnfamous1** [comment]
You can add it to raids using the configuration file. It also does in fact spawn in mansions, but only in the secret ritual rooms with the Evoker statue. You can change this via structure pack if you don’t like how rare they are, I won’t be bothering with that myself.
