### ISSUE TITLE
Redstone Golem AI not working well

### ISSUE THREAD

**Issue by Tinn04** [Thelnfamous1/Dungeons-Mobs#42]
Sometimes when I am fighting the Redstone Golem it just sits there, not moving. Or sometimes in a middle of a fight it just wanders off.  I can just hit it while standing in front of it for 5 seconds before it decides to hit back. This also occurs when it is fighting other mobs.

Also, if there are plans to update the Redstone Golem can you please add the following?

**Animation:**
I was also wondering if the attack animation could be updated to be similar to the actual Dungeons' animations where the arm is in full swing instead of a Minecraft Steve punch. Can the walking animation also be updated to where the arms are bent while running?

**Texture:**
Can the Redstone Golem's redstone parts be emissive? I think it would look a lot better.

**Attacks:**
Can you add the part where the golem charges the ground momentarily to summon Redstone Mines? Although make it take less time to charge so it wouldn't be so easy to just deal massive damage to it at that point

**Comment by Thelnfamous1** [comment]
Yes the Redstone Golem, being a larger mob, has issues with pathfinding, we will need to rework their AI

**Comment by BraveCaperCat** [comment]
> Sometimes when I am fighting the Redstone Golem it just sits there, not moving. Or sometimes in a middle of a fight it just wanders off.

It does that in minecraft dungeons itself!

**Comment by Patrigan** [comment]
Redstone Golem has been completely reworked in latest betas
