### ISSUE TITLE
SunkenSkeleton spawn crashing World

### ISSUE THREAD

**Issue by EggWhisper** [Thelnfamous1/Dungeons-Mobs#43]
[crash-2021-08-30_19.46.20-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/7080777/crash-2021-08-30_19.46.20-server.txt)

**Comment by EggWhisper** [comment]
I've gotten it to occur twice by going near the ocean and waiting so I believe the game's trying to spawn something but it can't and that causes it to crash.

**Comment by AbieTheFishman** [comment]
I believe I'm seeing the same issue.

dungeons_mobs-1.16.5-1.0.10.jar

[crash-2021-09-01_18.24.47-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/7094717/crash-2021-09-01_18.24.47-server.txt)

**Comment by Gazer10** [comment]
Same here, I even tried to disable spawning using the configured mod, but it kept randomly crashing near water. 

[crash-2021-09-13_14.32.28-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/7154100/crash-2021-09-13_14.32.28-server.txt)

**Comment by Patrigan** [comment]
It seems like your forge versions are all pretty old. Can you please try updating the version to at least 36.2.2?

**Comment by Thelnfamous1** [comment]
Yes, if you are getting a crash in the log that says "NoSuchMethod" it is because of you not using the at least Forge 36.2.2 which has necessary features for newer versions of the mod
