### ISSUE TITLE
crash when disable "enableRangedSpider"

### ISSUE THREAD

**Issue by bucketBrian** [Thelnfamous1/Dungeons-Mobs#48]
the world will immediately crash when spider spawn if conifg "enableRangedSpider" is disabled,
[crashreport -13-09-2021_23.08.19.zip](https://github.com/Thelnfamous1/Dungeons-Mobs/files/7158286/crashreport.-13-09-2021_23.08.19.zip)

**Comment by Patrigan** [comment]
Should not crash the game anymore in latest betas.
