### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by Congraz8961** [Thelnfamous1/Dungeons-Mobs#55]
I get this error on the console every time I start or restart the server

![image](https://user-images.githubusercontent.com/56209437/147156055-9a04b8e6-3e1a-4bed-a853-11af3cb7dc08.png)

**Comment by BraveCaperCat** [comment]
Provide a crash log

**Comment by Patrigan** [comment]
Will no longer happen on latest betas, as necromancers no longer summon wraiths
