### ISSUE TITLE
Too many empty lines in log in either this mod or its deps

### ISSUE THREAD

**Issue by EverettSummer** [Thelnfamous1/Dungeons-Mobs#56]
Trying this mod in both MP and SP, there are too many empty logs especially when fighting the raid.
I actually didn't find logger usage which empty lines in both this mod and its dependencies. but I am sure it's related to this mod or dungeon libraries, (geckolib not possible because it's not a server-side mod)
<img width="1278" alt="MultiMC_2022-01-03-000546-351" src="https://user-images.githubusercontent.com/55684557/147880137-0f6e3ed9-5af7-4abd-83ab-750b97c3d1c5.png">

https://paste.ee/p/qJUEe

**Comment by BraveCaperCat** [comment]
Where did you get this?
minecraft server hosting i presume!

**Comment by EverettSummer** [comment]
@BraveCaperCat The log is printed in both client and server consoles. I got the mod from Curseforge.
Anyway, the mod has some issues that can cause server hang issues.(cannot find log during the issue). So I already remove the mods

**Comment by Patrigan** [comment]
Fixed in latest beta
