### ISSUE TITLE
drowned skeleton crash

### ISSUE THREAD

**Issue by TellurianTech50** [Thelnfamous1/Dungeons-Mobs#58]
drowned skeletons are CTD every time one tries to spaw
[crash-2022-01-08_22.57.57-server.txt](https://github.com/Thelnfamous1/Dungeons-Mobs/files/7834448/crash-2022-01-08_22.57.57-server.txt)
and it seems that its a server side error

**Comment by Patrigan** [comment]
Fixed in latest betas
