### ISSUE TITLE
[beta] Debug print statement can cause lag on some systems

### ISSUE THREAD

**Issue by radiomike** [Thelnfamous1/Dungeons-Mobs#61]
Looks like you may have left this in by mistake. 

https://github.com/Thelnfamous1/Dungeons-Mobs/blob/2bfdb15b9b85db7bd11f67596a1ff5dadfce01a0/src/main/java/com/infamous/dungeons_mobs/blocks/CorruptedPyreBlock.java#L112

Someone added it to a pack I help out with and doing a spark profile shows it using ~75% of server time.

Profile for reference <https://spark.lucko.me/XF5Zto8Pze>

**Comment by Patrigan** [comment]
Should no longer give an issue as the corrupted pyre block no loger exists.
