### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by BraveCaperCat** [Thelnfamous1/Dungeons-Mobs#63]
Support/port to 1.12.2
Reason:
I need this mod as a replacement for [Dungeons Content](https://www.curseforge.com/minecraft/mc-mods/minecraft-dungeons-content) as it doesn't work with the latest forge version for 1.12.2 and is not supported (And i don't have a curseforge account for asking for updated forge support) as well as some other mods i have installed with it, require Forge version xx.xx.x.xxxx+
and that is a pain, and i need your dungeons-gear mod updated too

**Comment by BraveCaperCat** [comment]
But i don't use discord!

**Comment by Patrigan** [comment]
I'm terribly sorry for that. Github really isn't the place to have a conversation like that. But I do really urge you to move to 1.16.5 or even 1.18 (we'll be moving there soon as well).

I assure you almost all of the mods you really want exist in some form on 1.16.5 and soon also on 1.18. Really no reason to stay on 1.12.2.

**Comment by BraveCaperCat** [comment]
What about [Buildcraft,](mod.buildcraft.com) it's not yet available in 1.16.5+ yet on [curseforge,](https://www.curseforge.com/minecraft/mc-mods/buildcraft) but they do have 1.16.5 alphas in dev (Probably being developed right now!)
