### ISSUE TITLE
Server Startup Crash (Mob Enchantments Config)

### ISSUE THREAD

**Issue by GonKiIlua** [Thelnfamous1/Dungeons-Mobs#65]
Mod Version: dungeons_mobs-1.16.5-2.0.2-beta.jar
Forge Version: 36.2.2
[debug.log](https://github.com/Thelnfamous1/Dungeons-Mobs/files/8346333/debug.log)

Deleting the config file, 'dungeons-mobs-mob-enchantments-common.toml' resolves the issue, but once the server generates the config the next start-up crashes again. Also using the latest dungeons library beta.

**Comment by Esjitu** [comment]
Can confirm same thing is happening to me. Something very similar was happening with Dungeons Gear as well but the newest update seems to have fixed it. Mobs might just need a similar fix pushed?

**Comment by JaboyKoral** [comment]
Also having this same problem with Forge 36.2.20.

**Comment by JaboyKoral** [comment]
Can also confirm that it's happening with Forge 36.2.33, the most recent version for 1.16.5.

**Comment by Patrigan** [comment]
should be fixed on later betas
