### ISSUE TITLE
Missing Piglin Tag

### ISSUE THREAD

**Issue by WenXin20** [Thelnfamous1/Dungeons-Mobs#8]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Dungeon Mobs v1.0.3`

The gold armor/tools, such as the Gold Pillager Helmet, are missing the tag `#minecraft:piglin_loved`.

**Comment by Thelnfamous1** [comment]
They’re not truly gold, they are gold in name only as the term “gold” signifies the wearer’s rank
