### ISSUE TITLE
Quick-growing vine spaws inside houses

### ISSUE THREAD

**Issue by Gotyam** [Thelnfamous1/Dungeons-Mobs#9]
As title says, living in the jungle the vines spawn inside my (tree)house, despite it being perfectly torch-lit.

Edit: Also found a whisperer inside my house now, and would not be surprised if a poison-quill vine shows up next

**Comment by Thelnfamous1** [comment]
I'll look into this, likely because I forgot to put a light level limitation on their natural spawn function

**Comment by Thelnfamous1** [comment]
Fixed in dev, will be fixed in next release
